/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 C:\repos\alquimiafelina\public\avocado\food_avocado_01_4k.gltf -o C:\repos\alquimiafelina\src\components\Avocado.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Avocado(props) {
  const scroll = useScroll()
  const { nodes, materials } = useGLTF('/avocado/food_avocado_01_4k.gltf')

  useFrame((state, delta) => {
    // The offset is between 0 and 1, you can apply it to your models any way you like
    // darkmode-orb = from offset 1=<offset=>.5 , orb reduces size and moves to right

    const offset = 1 - scroll.offset

    // Will be 0 when the scrollbar is at the starting position,
    // then increase to 1 until 1 / 3 of the scroll distance is reached
    const a = scroll.range(0, 1 / 2)
    console.log(state)

    // the higher the a value (closer to 1), the smaller the avocado size
    // Calculate scaling factor based on a (higher a = smaller avocado)
    // Calculate camera distance based on a (higher a = closer camera, smaller view)

    const verticalMovement = 12 + (a * 25); // Adjust these values for desired effect
    const horizontalMovement = a * 5//new variable here

    // Set camera position (relative to the avocado)
    state.camera.position.set(verticalMovement, 6, 0);

    // Maintain camera lookAt point
    state.camera.lookAt(0, 0, 0);
  })

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.food_avocado_01.geometry} material={materials.food_avocado_01} />
    </group>
  )
}

useGLTF.preload('/avocado/food_avocado_01_4k.gltf')
