/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 C:\repos\alquimiafelina\public\avocado\food_avocado_01_4k.gltf -o C:\repos\alquimiafelina\src\components\Avocado.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Avocado(props) {
  const { nodes, materials } = useGLTF('/avocado/food_avocado_01_4k.gltf')

  return (
    <group {...props} dispose={null}>
      <mesh 
        geometry={nodes.food_avocado_01.geometry} 
        material={materials.food_avocado_01}/>
        scale={0.4}
    </group>
  )
}

useGLTF.preload('/avocado/food_avocado_01_4k.gltf')
